### ISSUE TITLE
travis-CI has timeouts

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/testbeam_analysis#80]
Message:
```
$ py.test --cov=testbeam_analysis

============================= test session starts ==============================

platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0

rootdir: /home/travis/build/SiLab-Bonn/testbeam_analysis, inifile:

plugins: cov-2.3.1

collected 34 items

testbeam_analysis/testing/test_alignment.py ...

testbeam_analysis/testing/test_analysis_utils.py .......

testbeam_analysis/testing/test_correlation_fixing.py .......

testbeam_analysis/testing/test_examples.py .

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

Maybe this can be solved with:
```
travis_wait py.test --cov=testbeam_analysis
```

See also: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by DavidLP** [comment]
Try it, I have no time for this now

**Comment by themperek** [comment]
Something is wrong with python 2.7.

**Comment by laborleben** [comment]
Adding `travis_wait` helped to fix the timeout. But now the overall process takes too long. Unit testing alone take up to 45min with Python 2.7. The CI process is then terminated due to the following reason: `The job exceeded the maximum time limit for jobs, and has been terminated.`

Interesting because Python 2.7 takes much more time than Python 3.6.

**Comment by DavidLP** [comment]
One can try calling `py.test --durations=10` during unit testing instead of `py.test --cov=testbeam_analysis` to show the 10 slowest unit tests and to check if my multithreading coverage hack makes troubles.

**Comment by laborleben** [comment]
Fixed.

**Comment by DavidLP** [comment]
Unfortunately not working. Sometimes travis hangs on python 2.7. Even 40 min timeout does not fix it.

**Comment by DavidLP** [comment]
I checked python 2/3 under Ubuntu 14.04LTS 64-bit running `nosetests`. Both took exactly 219 s.
A wild guess it memory consumption and/or `numba` bugs that lead to a different behaviour under python 2.7.

**Comment by DavidLP** [comment]
When running `nosetests` on travis`we use pretty much the available 4 Gb (or even 200 Mb above). This can lead to caching to disk decreasing run speed. 
![python2_7](https://user-images.githubusercontent.com/6951141/29869506-76555684-8d83-11e7-9d48-8de50d93809f.png)

When we switch to [sudo enable architecture](https://docs.travis-ci.com/user/reference/overview/) we have 8 Gb of RAM. Worth a try I guess.

**Comment by DavidLP** [comment]
Looks like Python 3 just stay below the limit. That would explain the difference. Funny.
![python3_0](https://user-images.githubusercontent.com/6951141/29873628-3ac81afa-8d94-11e7-8795-396539c50d05.png)

**Comment by DavidLP** [comment]
With 8 Gb more RAM the [execution time is the same for Python 2/3](https://travis-ci.org/SiLab-Bonn/testbeam_analysis/builds/269948396?utm_source=github_status&utm_medium=notification). Nice, hidden bug. Fixed in GUI branch.

**Comment by DavidLP** [comment]
Fixed in development
